id: P000823
initial_creation_type: ocr
created_at: 19/05/2021
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W3CN4863
  title: རྒྱལ་བའི་བསྟན་འགྱུར་ལྷ་ས་དཔར་མའི་དཀར་ཆག
  volumes:
    816c7a33c2db4fd3a48e0cc79d124bd6:
      image_group_id: I3CN8643
      title: ''
      base_file: v001.txt
  author: ''
